#pragma once

#define GENERAL_SCALE 1

#define SPACESHIP_MINIMUM_SPEED 0.05
#define SPACESHIP_MAXIMUM_SPEED 1.00

#define THIRD_PERSON_LEVERAGE 2.0f
#define THIRD_PERSON_BACK 3.5f

#define FRAME_TIME 20