#pragma once

#define GENERAL_SCALE 1

#define ROTATIONAL_VELOCITY_STEP 2.0

#define SPACESHIP_MINIMUM_SPEED 0.05
#define SPACESHIP_MAXIMUM_SPEED 1.00

#define THIRD_PERSON_LEVERAGE 2.0f
#define THIRD_PERSON_BACK 3.5f

#define FRAME_TIME 20

#define CAMERA_MODE_FIRST_PERSON 0
#define CAMERA_MODE_THIRD_PERSON 1
#define CAMERA_MODE_TOP_DOWN 2
#define CAMERA_MODE_SPACE_STATION 3
